name: bKits
version: '${project.version}'
main: pl.bonappetit.bkits.BKits
api-version: '1.16'
author: bonappetit
description: A simple plugin for creating kits for players to receive

commands:
  kit:
    aliases: [kits]
